.github/workflows/storybook.yaml, lib/components/Button/Button.tsx, package.json
- Fix `build_command` for the storybook's workflow; missing the `npm run`
- Fix the `prepare` script to include `npm run build`
- Replace the premade script with own to have more control (to deploy built storybook to GH Pages)
https://jira.eduuni.fi/browse/OPHJOD-241
=> OPHJOD-241: Fix storybook workflow and prepare step

lib/components/RadioButton/RadioButton.test.tsx, lib/components/RadioButton/RadioButton.tsx, lib/components/RadioButton/RadioButtonGroup.test.tsx, lib/components/RadioButton/RadioButtonGroup.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, lib/main.ts, package-lock.json, package.json
- Add RadioButton
- Add RadioButtonGroup
https://jira.eduuni.fi/browse/OPHJOD-261
=> OPHJOD-261: Add RadioButton & RadioButtonGroup components

lib/components/Expander/Expander.stories.tsx, lib/components/Expander/Expander.test.tsx, lib/components/Expander/Expander.tsx, lib/components/Expander/__snapshots__/Expander.test.tsx.snap, lib/main.ts
Add Expander component
Later if needed, add controlled state; able to remember and control the expanded/collapsed state programmatically.
https://jira.eduuni.fi/browse/OPHJOD-258
=> OPHJOD-258: Expander

lib/components/Toast/Toast.stories.ts, lib/components/Toast/Toast.test.tsx, lib/components/Toast/Toast.tsx, lib/components/Toast/__snapshots__/Toast.test.tsx.snap, lib/index.css, lib/symbols.css, tailwind.config.js
- Add toast component
https://jira.eduuni.fi/browse/OPHJOD-296
=> OPHJOD-296: Add toast component

lib/components/HeroCard/HeroCard.stories.tsx, lib/components/ResultsCard/ResultsCard.stories.ts
- Update Figma URLs in stories
=> OPHJOD-287: Update Figma URLs in stories

lib/components/InputField/InputField.stories.tsx, lib/components/InputField/InputField.test.tsx, lib/components/InputField/InputField.tsx, lib/components/InputField/__snapshots__/InputField.test.tsx.snap, lib/main.ts
- Add input field component
https://jira.eduuni.fi/browse/OPHJOD-294
=> OPHJOD-294: Add input field component

lib/components/Button/Button.stories.ts, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap
- Update button styles
https://jira.eduuni.fi/browse/OPHJOD-340
=> OPHJOD-340: Update button styles

lib/components/Accordion/Accordion.tsx, lib/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Remove the minus margin from the Accordion's icon button.
Was causing issues elsewhere where using Accordion component in Modal; horizontal scrolls appeared. And not seeing use for these margins.
https://jira.eduuni.fi/browse/OPHJOD-511
=> OPHJOD-511: Remove negative margin from Accordion icon button

lib/components/PopupList/PopupList.test.tsx, lib/components/PopupList/PopupList.tsx, lib/components/PopupList/__snapshots__/PopupList.test.tsx.snap
Update PopupList to match with the new design.
- Active item indicator is now using the blue background badge instead of the dot.
- Borders removed; using `box-shadow` now
- 
https://jira.eduuni.fi/browse/OPHJOD-558
=> OPHJOD-558: Update PopupList based on updated design

lib/components/NavigationBar/NavigationBar.stories.tsx, lib/components/NavigationBar/NavigationBar.test.tsx, lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
- Update to match with new design
- Removed `items` prop
- Items are no longer in the bar itself, but will be in the opened MegaMenu
- On mobile, the placement of MegaMenu opener is in different location than on desktop. At the end on mobile; at the start on desktop.
- Added a placeholder icon/place for the language change functionality to easily adjust the spacings/margins between items.
https://jira.eduuni.fi/browse/OPHJOD-565
=> OPHJOD-565: Update NavigationBar to match with new design

lib/components/Note/Note.stories.tsx, lib/components/Note/Note.test.tsx, lib/components/Note/Note.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap
* `href` and `readMoreText` props are replaced with `readMoreComponent` in `Note` component. Done to prevent full page reload when clicking the provided link. Now it's possible to use `<NavLink>` or similar in `Note` to use react router.
> [!NOTE]
> Read more functionality hasn't been used yet in yksilö UI, so no changes required there.
https://jira.eduuni.fi/browse/OPHJOD-603
=> OPHJOD-603: Use component instead of a link in Note read more button

lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap
* Added `size` and `bgColor` props to RoundButton
* Move the Label part into own component, because Sonar complained about cognitive complexity.
https://jira.eduuni.fi/browse/OPHJOD-634
=> OPHJOD-634: Add size and bgColor props to RoundButton

lib/components/Modal/Modal.tsx
* Fixed modal footer so it respects "justify-between" CSS class. Buttons should align properly now
https://jira.eduuni.fi/browse/OPHJOD-713
=> OPHJOD-713: Fix modal footer to respect justify between class

lib/components/Button/Button.tsx
* Fix accent button active and disabled styles
In the last PR these statuses were overlooked and it looked really bad in the UI.
https://jira.eduuni.fi/browse/OPHJOD-703
**Default**
**Hover**
**Active**
**Focus visible**
**Disabled**
=> OPHJOD-703: Fix accent button active and disabled styles

lib/components/Slider/Slider.stories.tsx, lib/components/Slider/Slider.test.tsx, lib/components/Slider/Slider.tsx
- Add `rightLabel` prop for Slider
- Tooltip updated to have logic when `rightLabel` prop is given.
- Output value of the component is still same: from **0** to **100** range
https://jira.eduuni.fi/browse/OPHJOD-705
=> OPHJOD-705: Add rightLabel prop for Slider

lib/components/Tag/Tag.stories.tsx, lib/components/Tag/Tag.test.tsx, lib/components/Tag/Tag.tsx, lib/components/Tag/__snapshots__/Tag.test.tsx.snap
* Add presentation variant to tag, that has no interactions
* Add story for a tag on multiple lines, as there's a design for it in Figma
* Updated design links in stories
https://jira.eduuni.fi/browse/OPHJOD-794
=> OPHJOD-794: Add presentation variant to Tag

lib/components/Checkbox/Checkbox.stories.tsx
* Fixed the `Storybook preview hooks can only be called inside decorators and story functions` error with checkbox stories. I'm not 100% sure what caused it, but using `useState` from `@storybook/preview-api` instead of React fixed the issue. I tried other components that used `React.useState` or `React.useEffect` but they didn't have any issues.
https://jira.eduuni.fi/browse/OPHJOD-879
=> OPHJOD-879: Fix storybook error with checkbox stories

tailwind.config.ts
Fix `attrib-title` to use px value instead of percentage because percentages are not valid values in CSS for letter-spacing.
In this case **1%** => font size 12px/100 = **0.12px**
https://jira.eduuni.fi/browse/OPHJOD-874
=> OPHJOD-874: Fix attrib-title to use px value for letterSpacing

lib/components/ConfirmDialog/ConfirmDialog.test.tsx, lib/components/Datepicker/Datepicker.stories.tsx, lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap, lib/components/Slider/Slider.test.tsx, package-lock.json, package.json
* Updated ARK UI to the latest version (4.12.0)
* Datepicker: Remove redundant `onInput` listener in text input that messed up the value
* Datepicker: Now uses `parseDate` from ARK UI to set the internal value in correct format as it was changed
* Datepicker: In latest version the date/number buttons became `div` elements instead of `button`. Used asChild to make them buttons again so that they can be disabled
* Slider: Unit test update
* ConfirmationDialog: Unit tests needed the actions to be wrapped in `act`
https://jira.eduuni.fi/browse/OPHJOD-861
=> OPHJOD-861: Update ark UI to version 4.12.0 and implement required changes

lib/components/Pagination/Pagination.tsx
Update `PageChangeDetails` to be explicitly told; not re-exported.
It seems that for some reason type checking still went to woods, what the previous fix #173 tried to already solve.
Explicitly now told the interface for `PageChangeDetails` as it seems that when it comes from the dependency's dependency it somehow goes wrong in the process when TypeScript/eslint is checking types.
This change just tells the same interface it should be deep down there.
Let's hope that this time it will work 🤞 
https://jira.eduuni.fi/browse/OPHJOD-945
https://jira.eduuni.fi/browse/OPHJOD-861
=> OPHJOD-945: Update PageChangeDetails to be explicitly told

lib/components/Accordion/Accordion.stories.tsx, lib/components/Accordion/Accordion.test.tsx, lib/components/Accordion/Accordion.tsx, lib/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- Remove `expandMoreText` & `expandLessText` props
- The `aria-expanded` gives this information to user when using screenreader
-  Update `aria-label` logic so that it works with both cases: when title is `ReactNode` or when it is just a `string`
- Add new `titleText` prop which is required when `title` is not a string
https://jira.eduuni.fi/browse/OPHJOD-952
=> OPHJOD-952: Update Accordion to work better with screenreader

lib/components/MediaCard/MediaCard.stories.tsx, lib/components/MediaCard/MediaCard.test.tsx, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap, lib/main.ts
Add MediaCard component.
Expecting to see adjustments when actually using the component later on.
- when it is vertical: keep the same size (width and height)
- when it is horizontal: allow width to be more freely (height locked)
https://jira.eduuni.fi/browse/OPHJOD-566
=> OPHJOD-566: Add MediaCard component

.eslintrc.cjs, lib/components/InputField/InputField.stories.tsx, lib/components/Modal/Modal.stories.tsx, lib/components/SelectionCard/SelectionCard.stories.tsx, lib/components/Slider/Slider.stories.tsx, lib/components/Slider/Slider.tsx, lib/components/Textarea/Textarea.stories.tsx
* Fixed contrast related accessability issues reported by AXE by putting labels inside `ArkSlider.Label` and moving those inside `ArkSlider.Root`
* Used typography values instead of pixel values for border roundings and font-sizes
* Removed the use of `ds-bg-todo` classes as it's not present in DS
* Removed stories from eslint ignore, as it caused `lint-staged` to fail
* Ignored some sonarjs ESLint rules
* ~~Disabled `sonarjs/rules-of-hooks` ESLint rule for slider stories~~
I also compared the slider against the previous version (https://opetushallitus.github.io/jod-design-system/?path=/docs/components-slider--documentation)  and it seemed to still match.
https://jira.eduuni.fi/browse/OPHJOD-1048
=> OPHJOD-1048: Fix contrast accessability issues in Slider component

.lintstagedrc.json, eslint.config.js, lib/components/SelectionCard/SelectionCard.stories.tsx, lib/components/SelectionCard/SelectionCard.tsx
This changes logic of the tooltip trigger.
Added optional infoIcon property, which allows user to customize look of the info button.
If component has infoIcon toolTip functionality is behind the info button. 
When infoIcon is missing toolTip is shown when selection card is hovered or focused and hidden on blur and mouse exit.
Other changes in this PR are related to eslint update, which caused errors in storybook rendering.
https://jira.eduuni.fi/browse/OPHJOD-1066
=> OPHJOD-1066: Changed tooltip logic

lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
* Fix the issue where checkbox checkmarks would be floating out of place when they were inside a scrolling modal
* The underlying cause was a misplaced `ds-relative`, it should have been in the parent element, and adjacent.
https://jira.eduuni.fi/browse/OPHJOD-1092
=> OPHJOD-1092: Fix checkbox checkmark not working properly inside a scrollable modal

lib/components/Modal/Modal.stories.tsx, lib/components/WizardProgress/WizardProgress.stories.tsx, lib/components/WizardProgress/WizardProgress.test.tsx, lib/components/WizardProgress/WizardProgress.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap
- Add more information for screenreader user
- `labelText` telling where user landed
- `stepText` tells what the number is 
- Made the existing `completedText` and `currentText` required as screenreader users should always have the same information.
-  Added a decorator for the story to be read in Finnish and to add one interactive element to a story, so it easier to get screenreader (at least VoiceOver to catch on to component)
**Includes breaking changes, so there is need for UI-side changes when updating to use updated version of DS on there.**
- As you can see from the screenshots, VoiceOver draws the text where the text would be if it is visible. It does not seem to honor the size of the element that Tailwind gives with the style.
- I tried to use `aria-label` but with that, …
=> OPHJOD-1089: Add more info for screenreader in WizardProgress

lib/components/Datepicker/Datepicker.stories.tsx, lib/components/Datepicker/Datepicker.test.tsx, lib/components/Datepicker/Datepicker.tsx
Add `translations` prop for `DatePicker` component.
Able to now have localized values for screenreader users.
As Ark-UI is used under the hood, these seems pretty tedious to use. Maybe we can use somekind of wrapper and give the `translations` properties in different way.
Because there is like 6 values (`clearTrigger,  content,  monthSelect, placeholder, presetTrigger, yearSelect`) that must given, as they are required by the Ark-UI which are not in use/or brings significant information.
**EDIT**: I made a change and picked only the used properties from the Ark-UI type of translations so that there is no need to give the unused translations properties everytime.
https://jira.eduuni.fi/browse/OPHJOD-1090
=> OPHJOD-1090: Add translations prop for DatePicker

lib/components/MediaCard/MediaCard.stories.tsx, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
- Update to have gray placeholder if no image is provided
- Update image to fit the area better
- Added optional `rating` & `ratingAriaLabel` props to show rating.
https://jira.eduuni.fi/browse/OPHJOD-1149
=> OPHJOD-1149: Update MediaCard

lib/components/MediaCard/MediaCard.stories.tsx, lib/components/MediaCard/MediaCard.test.tsx, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
- Add favorite button
- Update the sizes
- Remove the `variant` prop;  only `vertical` variant is left, so there is no longer prop for this.
Waiting for design files to be updated, so it might be possible that the _horizontal_ version is not needed as it was used before.
Currently favorite functionality is optional, so if it is undefined --> no heart icon is shown in the upper-right corner. Waiting for answers related to this, is it always wanted to have favorite-button.
Without any favorite info and when it is favorited
https://jira.eduuni.fi/browse/OPHJOD-1198
=> OPHJOD-1198: Update MediaCard

lib/components/LazyImage/LazyImage.stories.tsx, lib/components/LazyImage/LazyImage.test.tsx, lib/components/LazyImage/LazyImage.tsx, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
- Add LazyImage component
https://jira.eduuni.fi/browse/OPHJOD-1320
=> OPHJOD-1320: Add LazyImage component

lib/components/Checkbox/Checkbox.stories.tsx, lib/components/Checkbox/Checkbox.test.tsx, lib/components/Checkbox/Checkbox.tsx
- Update Checkbox disabled styles
- Update label logic (**BREAKING CHANGE**):
- if `label` is given, no need to give `aria-label`
- if no `label` is given, then `aria-label` is required
Chose to use the nearest color tokens to match with the current design and linked information of the ticket.
There has been talking that the Checkbox will be updated to different kind like in some ohjaaja layouts, so not too much change until then.
https://jira.eduuni.fi/browse/OPHJOD-1340
=> OPHJOD-1340: Update Checkbox disabled styles and label logic

lib/components/Checkbox/Checkbox.stories.tsx, lib/components/Checkbox/Checkbox.test.tsx, lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
This pull request adds a new feature to the Checkbox component to support indeterminate-state representation: checked, unchecked, and indeterminate. Updates include:
- Implementing logic to handle the indeterminate state with proper `aria-checked` accessibility attributes set to "mixed."
- Adding tests for all three states to ensure functionality and reliability.
- Providing Storybook examples, including a single three-state checkbox and a parent-child structure demonstrating indeterminate state behavior when controlling child checkboxes.
https://jira.eduuni.fi/browse/OPHJOD-1353
=> OPHJOD-1353: Add support, tests, and examples for indeterminate-state checkboxes

lib/components/Combobox/Combobox.tsx, lib/components/Combobox/__snapshots__/Combobox.test.tsx.snap
- Fix Combobox to use `div` instead of fragment (`<>`)
- Add missing `ds:` to one existing classname
- Update snapshots
https://jira.eduuni.fi/browse/OPHJOD-1398
=> OPHJOD-1398: Fix Combobox to use div instead of fragment

lib/components/Accordion/Accordion.tsx, lib/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- Fix Accordion bottom margin when children are hidden
- Fix initialState property name
https://jira.eduuni.fi/browse/OPHJOD-1439
=> OPHJOD-1439: Fix Accordion bottom margin when children are hidden

lib/components/Modal/Modal.stories.tsx, lib/components/Modal/Modal.tsx
* Allow the main modal content to take up the full width while showing the progress component when sidebar is not defined
https://jira.eduuni.fi/browse/OPHJOD-1339
=> OPHJOD-1339: Allow main modal content to take all available width with progress bar

lib/theme.css
In Tailwind version 4.0.5, a change (https://github.com/tailwindlabs/tailwindcss/pull/16211) was introduced that causes only the used variables to be included in the final CSS. As a result, a component using the Design System cannot use any theme variable directly (e.g., var(--ds-color-secondary-3)) unless that variable has been used in one of the Design System's components. However, an option called static has been added to the theme rule, which, when used, includes all theme variables in the final CSS.
https://jira.eduuni.fi/browse/OPHJOD-1440
=> OPHJOD-1440: Add static theme option to generate all CSS variables

lib/components/Tag/Tag.test.tsx, lib/components/Tag/Tag.tsx, lib/components/Tag/__snapshots__/Tag.test.tsx.snap, package.json
Updated the Tag component cursor behavior to ensure it does not appear clickable (i.e., no pointer cursor) when `variant === 'presentation'`. This enhances the user interface by reflecting the non-clickable nature of this specific variant.
https://jira.eduuni.fi/browse/OPHJOD-1451
=> OPHJOD-1451: Change Tag component cursor for 'presentation' variant

lib/components/Button/Button.stories.tsx, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap
- Update Button styles
- Add new variant `red-delete` and story for it
- Background red was not yet listed in design, so hardcoding the color until then™
- explicitly set font based on size; like listed on design
- Removed the `text-button-md-mobile` token usage as the token no longer exists
https://jira.eduuni.fi/browse/OPHJOD-1525
=> OPHJOD-1525: Update Button styles

lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
Update the MediaCard's horizontal version
- use the min-heights like in the design to get more room in smaller breakpoints
- remove the padding that was caused when tags wrapped to next line
There is currently no limit to selected tags or the lengths so it might still break if content producers will write too much.
https://jira.eduuni.fi/browse/OPHJOD-1600
=> OPHJOD-1600: Update MediaCard's horizontal version

lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/components/HeroCard/__snapshots__/HeroCard.test.tsx.snap
Set `ds:text-black` in button for the white variant. The bug was that buttons in HeroCard didn't have visible text (white button, white text). 
https://jira.eduuni.fi/browse/OPHJOD-1769
=> OPHJOD-1769: Add black font color when button variant is white

lib/components/NavigationMenu/NavigationMenu.stories.tsx, lib/components/NavigationMenu/NavigationMenu.test.tsx, lib/components/NavigationMenu/NavigationMenu.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap, lib/components/NavigationMenu/components/MenuList.tsx, lib/components/NavigationMenu/index.ts
* Add the ability to set a title for menu items, and rename `menuItems` prop to `menuSection`.
* Rename incorrectly named serviceDirectory* props to portal* 
https://jira.eduuni.fi/browse/OPHJOD-1714
=> OPHJOD-1714: Add the ability to set a title for menu section and rename props

lib/main.ts, package.json
Noticed that importing the icons in consuming apps was kinda stupid: `import { icons } from '@jod/design-system'` -> `<icons.JodHome />`
Changed the configuration so the imports now work like: `import { JodHome } from '@jod/design-system/icons'`
Tested that this works using `npm link`
https://jira.eduuni.fi/browse/OPHJOD-1740
=> OPHJOD-1740: Export icons properly

lib/components/Button/Button.tsx, lib/components/Note/Note.tsx, lib/components/Note/NoteStack.test.tsx, lib/components/Note/NoteStack.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap
* Note stack now shows the "show all" in correct color
* Added animation for collapsing
* An unrelated disabled state fix for button
https://jira.eduuni.fi/browse/OPHJOD-1784
=> OPHJOD-1784: Fix the logic for "show all" button in note stack

lib/components/Button/Button.stories.tsx, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/components/HeroCard/__snapshots__/HeroCard.test.tsx.snap
Add `aria-label` for a Button component.
When using only the icon mode, screenreader user couldn't know what is the button for. Uses the same label that is already required, so no functionality changed.
https://jira.eduuni.fi/browse/OPHJOD-1826
=> OPHJOD-1826: Add aria-label for the Button

lib/components/NavigationMenu/components/MenuList.tsx
Fix the focus stealing of MenuList.
Example case where it was causing issue is when used in yksilo-ui and having the submenu. It stealed the focus to always first item in the list on every page refresh.
https://jira.eduuni.fi/browse/OPHJOD-1858
https://jira.eduuni.fi/browse/OPHJOD-1840
=> OPHJOD-1858: Fix MenuList focus stealing issue

lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap, lib/components/NavigationMenu/components/Backdrop.tsx
Display `NavigationMenu` on the right side of the screen. Tested via `npm link` in yksilö UI
https://jira.eduuni.fi/browse/OPHJOD-1895
=> OPHJOD-1895: Show navigation menu on the left side of the screen

lib/components/Button/Button.stories.tsx, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap
* Fix sm button size, it was 26px but in the design it's 32px
* Add gray button variant back. There was no design for disabled state, so I took a guess.
https://jira.eduuni.fi/browse/OPHJOD-1953
=> OPHJOD-1953: Fix sm button size and reintroduce gray button variant

lib/components/NavigationMenu/NavigationMenu.stories.tsx, lib/components/NavigationMenu/NavigationMenu.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap, lib/components/NavigationMenu/components/MenuList.tsx, lib/components/NavigationMenu/components/PortalLink.tsx, lib/utils.ts
* Updated the "palveluportaali" variant colorings, it's now gray instead of yellowish.
* Make menuSection optional and don't display a separator if menuSection is not defined (OPHJOD-1942)
https://jira.eduuni.fi/browse/OPHJOD-2241
https://jira.eduuni.fi/browse/OPHJOD-1942
Without menu section:
=> OPHJOD-2241: Update default colors for portal variant and remove extra separator if menu section is not defined

lib/components/NavigationMenu/components/MenuList.tsx
In `PageNavigation`, the list items selected background now take the whole available width, just like the focus outline
https://jira.eduuni.fi/browse/OPHJOD-1809
=> OPHJOD-1809: Fix PageNavigation item highlight width

lib/components/Tag/Tag.stories.tsx, lib/components/Tag/Tag.tsx, lib/components/Tooltip/TooltipContent.tsx
- Add tooltip support to Tag
https://jira.eduuni.fi/browse/OPHJOD-2121
=> OPHJOD-2121: Add tooltip support to Tag
