.eslintrc.cjs, package-lock.json, package.json
- Rename package
- Ignore `storybook-static` for eslint
https://jira.eduuni.fi/browse/OPHJOD-260
=> OPHJOD-260: Rename package + ignore storybook-static on eslint

lib/components/RoundButton/RoundButton.stories.ts, lib/components/RoundButton/RoundButton.test.tsx, lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.stories.tsx, lib/components/RoundLinkButton/RoundLinkButton.test.tsx, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap, lib/main.ts
- Add RoundButton
- Add RoundLinkButton
https://jira.eduuni.fi/browse/OPHJOD-256
=> OPHJOD-256: Add RoundButton & RoundLinkButton

.gitignore
- Add coverage folder to Git ignore
https://jira.eduuni.fi/browse/OPHJOD-283
=> OPHJOD-283: Add coverage folder to Git ignore

lib/components/Button/Button.stories.ts, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/components/DropdownMenu/DropdownMenu.test.tsx, lib/components/DropdownMenu/DropdownMenu.tsx, lib/components/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap, package-lock.json, package.json
- Remove classnames
https://jira.eduuni.fi/browse/OPHJOD-281
=> OPHJOD-281: Remove classnames

lib/components/ColorCard/ColorCard.stories.tsx, lib/components/ColorCard/ColorCard.test.tsx, lib/components/ColorCard/ColorCard.tsx
- Add color card component
https://jira.eduuni.fi/browse/OPHJOD-282
=> OPHJOD-282: Add color card component

lib/components/DropdownMenu/DropdownMenu.test.tsx, lib/components/DropdownMenu/DropdownMenu.tsx, lib/components/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap
- Refactor dropdown menu component
https://jira.eduuni.fi/browse/OPHJOD-286
=> OPHJOD-286: Refactor dropdown menu component

lib/main.ts
- Export ColorCard component from the design system.
- Arranged other exported components to alphabetic order for easier figuring out.
https://jira.eduuni.fi/browse/OPHJOD-312
=> OPHJOD-312: Update ColorCard to be exported

lib/components/DropdownMenu/DropdownMenu.tsx, lib/components/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap, lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap, lib/components/TextCard/TextCard.tsx, lib/components/TextCard/__snapshots__/TextCard.test.tsx.snap, tailwind.config.js
- Update colors, fonts and spacings
- TODO: Fix components in a separate pull request
=> OPHJOD-287: Update colors, fonts and spacings

lib/components/ColorCard/ColorCard.test.tsx, lib/components/ColorCard/ColorCard.tsx
Add `href` prop to ColorCard component
https://jira.eduuni.fi/browse/OPHJOD-313
=> OPHJOD-313: Add href prop to ColorCard component

lib/components/HeroCard/HeroCard.stories.tsx, lib/components/HeroCard/HeroCard.test.tsx, lib/components/HeroCard/HeroCard.tsx, lib/main.ts
- Rename color card to hero card
- Use Tailwind CSS rules and fix href
=> OPHJOD-287: Rename color card and use Tailwind CSS rules

tailwind.config.js
=> OPHJOD-287: Fix letter spacings

lib/components/NavigationBar/NavigationBar.stories.tsx, lib/components/NavigationBar/NavigationBar.test.tsx, lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
- Use Tailwind CSS rules and remove placeholder avatar
=> OPHJOD-287: Use Tailwind CSS rules and remove placeholder avatar

lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
Improve the RoundLinkButton's clickable area.
**FYI**: _Branch name typoed and have wrong ticket number_
https://jira.eduuni.fi/browse/OPHJOD-285
=> OPHJOD-285: Update RoundLinkButton clickable area

lib/components/DropdownMenu/DropdownMenu.test.tsx, lib/components/Expander/Expander.test.tsx, lib/components/HeroCard/HeroCard.test.tsx, lib/components/NavigationBar/NavigationBar.test.tsx, lib/components/RadioButton/RadioButton.test.tsx, lib/components/RadioButton/RadioButtonGroup.test.tsx, lib/components/ResultsCard/ResultsCard.test.tsx, lib/components/RoundButton/RoundButton.test.tsx, lib/components/RoundLinkButton/RoundLinkButton.test.tsx, lib/components/Toast/Toast.test.tsx
- Remove unnecessary cleanup calls
https://jira.eduuni.fi/browse/OPHJOD-316
=> OPHJOD-316: Remove unnecessary cleanup calls

lib/components/Note/Note.stories.tsx, lib/components/Note/Note.test.tsx, lib/components/Note/Note.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap
- Add note component
https://jira.eduuni.fi/browse/OPHJOD-295
=> OPHJOD-295: Add note component

.storybook/preview.ts, lib/components/Footer/Footer.stories.tsx, lib/components/Footer/Footer.test.tsx, lib/components/Footer/Footer.tsx, lib/components/Footer/__snapshots__/Footer.test.tsx.snap, lib/main.ts, tailwind.config.js
- Add footer component
- Add mobile viewport
https://jira.eduuni.fi/browse/OPHJOD-323
=> OPHJOD-323: Add footer component

lib/components/RoundButton/RoundButton.stories.tsx, lib/components/RoundButton/RoundButton.test.tsx, lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.stories.tsx, lib/components/RoundLinkButton/RoundLinkButton.test.tsx, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
- Clickable areas adjusted; now whole area is clickable, not just the round part.
- Uses icon names from the Google Material Design.
- Removed old hover/focus styles that was done before designs had them.
_Branch name is remnant from the merged JIRA issue._
https://jira.eduuni.fi/browse/OPHJOD-319
=> OPHJOD-319: RoundLinkButton & RoundButton icon change and click area adjustments

lib/components/Button/Button.stories.ts, lib/components/Button/Button.test.tsx, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap
- Update button component
https://jira.eduuni.fi/browse/OPHJOD-288
=> OPHJOD-288: Update button component

lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
- Add avatar placeholder image
https://jira.eduuni.fi/browse/OPHJOD-329
=> OPHJOD-329: Add avatar placeholder image

lib/components/RadioButton/RadioButton.stories.tsx, lib/components/RadioButton/RadioButton.tsx, lib/components/RadioButton/RadioButtonGroup.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
- Update RadioButton + RadioButtonGroup styles
- Add Storybook page for RadioButtonGroup (also showing the RadioButton as there is no sense separating them)
https://jira.eduuni.fi/browse/OPHJOD-328
=> OPHJOD-328: Update RadioButton + RadioButtonGroup styles

lib/components/Button/Button.stories.ts, lib/components/DropdownMenu/DropdownMenu.stories.ts, lib/components/Expander/Expander.stories.tsx, lib/components/RoundButton/RoundButton.stories.tsx, lib/components/RoundLinkButton/RoundLinkButton.stories.tsx
- Remove primitives category
https://jira.eduuni.fi/browse/OPHJOD-322
=> OPHJOD-322: Remove primitives category

lib/components/NavigationBar/NavigationBar.stories.tsx, lib/components/NavigationBar/NavigationBar.test.tsx, lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
- Add logo prop to navigation bar
https://jira.eduuni.fi/browse/OPHJOD-347
=> OPHJOD-347: Add logo prop to navigation bar

lib/components/Expander/Expander.test.tsx, lib/components/Note/Note.test.tsx, lib/components/Note/Note.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap, lib/components/RadioButton/RadioButton.test.tsx, lib/components/RadioButton/RadioButtonGroup.test.tsx, lib/components/ResultsCard/ResultsCard.test.tsx, lib/components/Toast/Toast.test.tsx, lib/hooks/useMediaQueries/index.ts, lib/symbols.css, lib/vite-env.d.ts, package.json, tailwind.config.ts, tsconfig.node.json, vite.config.ts, vitest.setup.ts
- Add mobile responsive note
https://jira.eduuni.fi/browse/OPHJOD-343
=> OPHJOD-343: Add mobile responsive note

lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
Add hover style for RoundLinkButton and RoundButton based on a design.
https://jira.eduuni.fi/browse/OPHJOD-300
=> OPHJOD-300: Add hover style for RoundButton/RoundLinkButton

lib/components/Tooltip/Tooltip.stories.tsx, lib/components/Tooltip/Tooltip.tsx, lib/components/Tooltip/TooltipContent.tsx, lib/components/Tooltip/TooltipTrigger.tsx, lib/components/Tooltip/utils.ts, package-lock.json, package.json
Add Tooltip component
https://jira.eduuni.fi/browse/OPHJOD-293
=> OPHJOD-293: Add Tooltip component

lib/components/Footer/Footer.tsx, lib/components/Footer/__snapshots__/Footer.test.tsx.snap, lib/components/Note/Note.tsx, lib/hooks/useMediaQueries/index.ts, lib/main.ts
- Refactor footer to use forwardRef
https://jira.eduuni.fi/browse/OPHJOD-334
=> OPHJOD-334: Refactor footer to use forwardRef

lib/components/Slider/Slider.stories.tsx, lib/components/Slider/Slider.test.tsx, lib/components/Slider/Slider.tsx, lib/main.ts, package-lock.json, package.json
Add Slider component
https://jira.eduuni.fi/browse/OPHJOD-292
=> OPHJOD-292: Add Slider component

.storybook/preview.ts, lib/docs/Colors.mdx, lib/docs/GettingStarted.mdx, lib/docs/Spacing.mdx
- Add some docs from Figma
https://jira.eduuni.fi/browse/OPHJOD-338
=> OPHJOD-338: Add some docs from Figma

lib/components/HeroCard/HeroCard.tsx
- Refactor hero card to use icon instead of text arrow
https://jira.eduuni.fi/browse/OPHJOD-393
=> OPHJOD-393: Refactor hero card to use icon instead of text arrow

lib/components/Tag/Tag.stories.tsx, lib/components/Tag/Tag.test.tsx, lib/components/Tag/Tag.tsx, lib/components/Tag/__snapshots__/Tag.test.tsx.snap, lib/components/TagsInput/TagsInput.stories.tsx, lib/components/TagsInput/TagsInput.test.tsx, lib/components/TagsInput/TagsInput.tsx, lib/components/TagsInput/__snapshots__/TagsInput.test.tsx.snap, lib/main.ts, lib/symbols.css, package-lock.json, package.json
- Add Tag component
- Add TagsInput component
- Add bold variant for size-24 icon
https://jira.eduuni.fi/browse/OPHJOD-298
=> OPHJOD-298: Add Tag & TagsInput component

lib/components/SkipLink/SkipLink.stories.tsx, lib/components/SkipLink/SkipLink.test.tsx, lib/components/SkipLink/SkipLink.tsx, lib/components/SkipLink/__snapshots__/SkipLink.test.tsx.snap, lib/main.ts
Add SkipLink component
https://jira.eduuni.fi/browse/OPHJOD-384
=> OPHJOD-384: Add SkipLink component

lib/components/NavigationBar/NavigationBar.stories.tsx, lib/components/NavigationBar/NavigationBar.test.tsx, lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
- Update login button and icon
https://jira.eduuni.fi/browse/OPHJOD-404
=> OPHJOD-404: Update login button and icon

lib/components/Checkbox/Checkbox.stories.tsx, lib/components/Checkbox/Checkbox.test.tsx, lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, lib/main.ts
- Add checkbox component
https://jira.eduuni.fi/browse/OPHJOD-413
=> OPHJOD-413: Add checkbox component

lib/components/Pagination/Pagination.stories.tsx, lib/components/Pagination/Pagination.test.tsx, lib/components/Pagination/Pagination.tsx, lib/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Created the Pagination component. It was named Pager in the ticket and figma, but we decided a more standard name is better.
https://jira.eduuni.fi/browse/OPHJOD-291
=> OPHJOD-291: Create Pagination component

lib/components/Expander/Expander.tsx, lib/components/Expander/__snapshots__/Expander.test.tsx.snap, lib/components/RadioButton/RadioButton.tsx, lib/components/RadioButton/RadioButtonGroup.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, package-lock.json, package.json
- Update headlessui library and the usage of it to not use deprecated API anymore.
- Update Expander component to use icon from material; no longer hardcoded svg
https://jira.eduuni.fi/browse/OPHJOD-438
=> OPHJOD-438: Update headlessui to 2.x version and update usage

lib/components/Pagination/Pagination.tsx, lib/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- Refactor pagination styles and accessibility
https://jira.eduuni.fi/browse/OPHJOD-291
=> OPHJOD-291: Refactor pagination styles and accessibility

lib/components/WizardProgress/WizardProgress.stories.tsx, lib/components/WizardProgress/WizardProgress.test.tsx, lib/components/WizardProgress/WizardProgress.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap
- Add wizard progress component
https://jira.eduuni.fi/browse/OPHJOD-289
=> OPHJOD-289: Add wizard progress component

lib/components/PopupList/PopupList.stories.tsx, lib/components/PopupList/PopupList.test.tsx, lib/components/PopupList/PopupList.tsx, lib/components/PopupList/__snapshots__/PopupList.test.tsx.snap, lib/main.ts
* Created PopupList component
https://jira.eduuni.fi/browse/OPHJOD-422
=> OPHJOD-422 Create PopupList component

lib/components/ActiveIndicator/ActiveIndicator.stories.tsx, lib/components/ActiveIndicator/ActiveIndicator.test.tsx, lib/components/ActiveIndicator/ActiveIndicator.tsx, lib/components/ActiveIndicator/__snapshots__/ActiveIndicator.test.tsx.snap, lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, lib/components/PopupList/PopupList.tsx, lib/main.ts
Created and implemented a generic ActiveIndicator component
https://jira.eduuni.fi/browse/OPHJOD-440
=> OPHJOD-440: Create and implement ActiveIndicator component

lib/components/PopupList/PopupList.stories.tsx, lib/components/PopupList/PopupList.test.tsx, lib/components/PopupList/PopupList.tsx, lib/components/PopupList/__snapshots__/PopupList.test.tsx.snap
* Refactor of the PopupList component. In previous PR I forgot to set the background, and also there is a need for the ability to have both links and buttons in the list.
https://jira.eduuni.fi/browse/OPHJOD-422
=> OPHJOD-422: PopupList refactoring

lib/components/Modal/Modal.stories.tsx, lib/components/Modal/Modal.tsx
Add mobile version of the Modal component.
https://jira.eduuni.fi/browse/OPHJOD-442
=> OPHJOD-442: Add Modal component, mobile

lib/components/Accordion/Accordion.stories.tsx, lib/components/Accordion/Accordion.test.tsx, lib/components/Accordion/Accordion.tsx, lib/components/Accordion/__snapshots__/Accordion.test.tsx.snap, lib/main.ts
Add Accordion component; mostly moved from the UI-side to here with some changes.
https://jira.eduuni.fi/browse/OPHJOD-437
=> OPHJOD-437: Add Accordion component

lib/main.ts
Add export for Modal component as it was forgotten.
https://jira.eduuni.fi/browse/OPHJOD-449
=> OPHJOD-449: Add export for Modal component

lib/components/Datepicker/Datepicker.stories.tsx, lib/components/Datepicker/Datepicker.test.tsx, lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap
* Datepicker component. More of a skeleton at this point as there currently isn't any design for it. Uses the Ark-UI component as base: https://ark-ui.com/react/docs/components/date-picker
https://jira.eduuni.fi/browse/OPHJOD-441
=> OPHJOD-441: Datepicker component MVP

lib/components/ConfirmDialog/ConfirmDialog.stories.tsx, lib/components/ConfirmDialog/ConfirmDialog.test.tsx, lib/components/ConfirmDialog/ConfirmDialog.tsx, lib/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap, lib/main.ts
Add ConfirmationDialog component
https://jira.eduuni.fi/browse/OPHJOD-446
=> OPHJOD-446: Add ConfirmationDialog component

.github/workflows/build.yml, .gitignore, README.md, lib/symbols.css, vite.config.ts
- Sync third party assets from S3 bucket
https://jira.eduuni.fi/browse/OPHJOD-315
=> OPHJOD-315: Sync third party assets from S3 bucket

lib/components/Slider/Slider.stories.tsx, lib/components/Slider/Slider.tsx
- Fix the Slider value not updating correctly
- Update Storybook story
- Adjust width
https://jira.eduuni.fi/browse/OPHJOD-489
=> OPHJOD-489: Adjust Slider component functionalities

package.json
- Add lib to package files
https://jira.eduuni.fi/browse/OPHJOD-495
=> OPHJOD-495: Add lib to package files

lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap
- Refactor datepicker for improved accessibility
https://jira.eduuni.fi/browse/OPHJOD-441
=> OPHJOD-441: Refactor datepicker for improved accessibility

lib/components/Modal/Modal.tsx
- Update Modal for desktop to take full height
- Update Modal's padding to lower on mobile
- Update Modal's border on mobile
_Commits separated for now, merging them later/on rebase._
https://jira.eduuni.fi/browse/OPHJOD-455
=> OPHJOD-455: Modal adjustments

lib/components/Modal/Modal.tsx
Update Modal's `onClose` prop to be optional.
https://jira.eduuni.fi/browse/OPHJOD-519
=> OPHJOD-519: Update Modal's onClose prop to be optional

lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
Add `hideLabel` prop for RoundLinkButton & RoundButton
https://jira.eduuni.fi/browse/OPHJOD-526
=> OPHJOD-526: Add hideLabel prop for RoundLinkButton & RoundButton

.storybook/preview-head.html, lib/components/Accordion/Accordion.tsx, lib/components/Accordion/__snapshots__/Accordion.test.tsx.snap, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/components/ConfirmDialog/ConfirmDialog.tsx, lib/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap, lib/components/Note/Note.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap, lib/components/ResultsCard/ResultsCard.tsx, lib/components/ResultsCard/__snapshots__/ResultsCard.test.tsx.snap, lib/components/Slider/Slider.tsx, lib/components/WizardProgress/WizardProgress.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap, tailwind.config.ts
Typography design tokens updated
https://jira.eduuni.fi/browse/OPHJOD-541
=> OPHJOD-541: Update typography tokens

lib/components/Slider/Slider.stories.tsx, lib/components/Slider/Slider.test.tsx, lib/components/Slider/Slider.tsx
Adjust Slider to match with the updated design
https://jira.eduuni.fi/browse/OPHJOD-542
=> OPHJOD-542: Update Slider to use updated design

lib/components/InputField/InputField.tsx
Update InputField to match with the updated design.
https://jira.eduuni.fi/browse/OPHJOD-574
=> OPHJOD-574: Update InputField to use updated design

lib/components/Modal/Modal.stories.tsx, lib/components/Modal/Modal.tsx
Updated modal component to match latest design
https://jira.eduuni.fi/browse/OPHJOD-575
=> OPHJOD-575: Update modal to match current design

lib/components/ConfirmDialog/ConfirmDialog.stories.tsx, lib/components/ConfirmDialog/ConfirmDialog.tsx, lib/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap
Update ConfirmDialog component to match latest design
https://jira.eduuni.fi/browse/OPHJOD-559
=> OPHJOD-559: Update ConfirmDialog component to match latest design

lib/components/WizardProgress/WizardProgress.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap
Update WizardProgress to match with the updated design.
https://jira.eduuni.fi/browse/OPHJOD-555
=> OPHJOD-555: UpdateWizardProgress to match the updated design

lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/docs/Colors.mdx, tailwind.config.ts
* Updated the button component to match current design. Changes were quite subtle, only border rounding on large buttons and outline color for delete buttons changed.
https://jira.eduuni.fi/browse/OPHJOD-552
=> OPHJOD-552: Update button component

lib/components/PopupList/PopupList.stories.tsx, lib/components/PopupList/PopupList.test.tsx, lib/components/PopupList/PopupList.tsx, lib/components/PopupList/__snapshots__/PopupList.test.tsx.snap, lib/main.ts
Refactored PopupList component to be more of a wrapper that styles the list and it's items. The list items are now components that are passed via the children prop.
https://jira.eduuni.fi/browse/OPHJOD-584
=> OPHJOD-584: Refactor popupList to be more of a wrapper type component

lib/components/HeroCard/HeroCard.stories.tsx, lib/components/HeroCard/HeroCard.test.tsx, lib/components/HeroCard/HeroCard.tsx
HeroCard design changes
https://jira.eduuni.fi/browse/OPHJOD-549
=> OPHJOD-549: HeroCard design update

lib/components/Toast/Toast.stories.ts, lib/components/Toast/Toast.tsx, lib/components/Toast/__snapshots__/Toast.test.tsx.snap, tailwind.config.ts
* Toast component visual update. Only the font color was changed.
https://jira.eduuni.fi/browse/OPHJOD-568
=> OPHJOD-568: Toast component visual update

lib/components/SelectionCard/SelectionCard.stories.tsx, lib/components/SelectionCard/SelectionCard.test.tsx, lib/components/SelectionCard/SelectionCard.tsx, lib/main.ts
* Created SelectionCard component (previously known as TargetTypeCard)
* 
https://jira.eduuni.fi/browse/OPHJOD-563
=> OPHJOD-563: Create SelectionCard component

lib/components/Tooltip/utils.ts
* Prevent tooltip arrow from floating above rounded corners
https://jira.eduuni.fi/browse/OPHJOD-595
=> OPHJOD-595: Take border radius into account with tooltip arrow placement

.storybook/preview.ts, lib/components/Note/Note.stories.tsx, lib/components/Note/Note.test.tsx, lib/components/Note/Note.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap
`Note` component design update
https://jira.eduuni.fi/browse/OPHJOD-567
=> OPHJOD-567: Note component visual update

lib/components/Accordion/Accordion.stories.tsx, lib/components/Accordion/Accordion.tsx, lib/components/Accordion/__snapshots__/Accordion.test.tsx.snap
* Accordion component updated
https://jira.eduuni.fi/browse/OPHJOD-556
=> OPHJOD-556: Accordion design update

lib/components/RadioButton/RadioButtonGroup.tsx
* Make the label in RadioButtonGroup optional
https://jira.eduuni.fi/browse/OPHJOD-594
=> OPHJOD-594: Make the label in RadioButtonGroup optional

lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap
Poppins font is now used in all button variants
https://jira.eduuni.fi/browse/OPHJOD-607
=> OPHJOD-607: Poppins font in all button variants

lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Checkbox component design update
https://jira.eduuni.fi/browse/OPHJOD-605
=> OPHJOD-605: Checkbox design update

lib/components/RadioButton/RadioButton.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
RadioButton design update
https://jira.eduuni.fi/browse/OPHJOD-606
=> OPHJOD-606: RadioButton design update

.storybook/preview.ts
Match the storybook preview background color with yksilö ui
https://jira.eduuni.fi/browse/OPHJOD-613
=> OPHJOD-613: Match the storybook preview background color with yksilö ui

.gitignore, lib/components/Checkbox/Checkbox.tsx, lib/components/ConfirmDialog/ConfirmDialog.tsx, lib/components/Datepicker/Datepicker.tsx, lib/components/HeroCard/HeroCard.tsx, lib/components/InputField/InputField.tsx, lib/components/Modal/Modal.stories.tsx, lib/components/Modal/Modal.tsx, lib/components/Note/Note.tsx, lib/components/Pagination/Pagination.tsx, lib/components/PopupList/PopupList.stories.tsx, lib/components/PopupList/PopupList.tsx, lib/components/RadioButton/RadioButtonGroup.tsx, lib/components/RoundButton/RoundButton.tsx, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/SelectionCard/SelectionCard.tsx, lib/components/Slider/Slider.tsx, lib/components/Tag/Tag.tsx, lib/components/Toast/Toast.tsx, lib/components/Tooltip/Tooltip.tsx
- Add some descriptions for components
https://jira.eduuni.fi/browse/OPHJOD-324
=> OPHJOD-324: Add some descriptions for components

package-lock.json, package.json
Update Vite to latest version
https://jira.eduuni.fi/browse/OPHJOD-615
=> OPHJOD-615: Update Vite

lib/components/HeroCard/HeroCard.tsx, tailwind.config.ts
- Add md screen
https://jira.eduuni.fi/browse/OPHJOD-402
=> OPHJOD-402: Add md screen

.github/workflows/build.yml
- Copy font from S3 to assets
https://jira.eduuni.fi/browse/OPHJOD-620
=> OPHJOD-620: Copy font from S3 to assets

lib/components/Tooltip/TooltipContent.tsx
Update Tooltip to smaller rounded.
Background color left black as wanted.
https://jira.eduuni.fi/browse/OPHJOD-623
=> OPHJOD-623: Update Tooltip to smaller rounded

lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
Update background color of RoundButton & RoundLinkButton.
Fix the hover; was able to hover label and circle shape separately.
https://jira.eduuni.fi/browse/OPHJOD-616
=> OPHJOD-616: Update background color of RoundButton & RoundLinkButton

lib/components/Pagination/Pagination.tsx, lib/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Change background color and font in Pagination component.
https://jira.eduuni.fi/browse/OPHJOD-622
=> OPHJOD-622: Update pagination component to match design

lib/components/PathProgress/PathProgress.stories.tsx, lib/components/PathProgress/PathProgress.tsx, lib/components/PopupList/PopupList.stories.tsx, lib/main.ts, lib/utils.test.ts, lib/utils.ts
* Initial version for PathProgress. There are still design/functionality questions to be resolved before it can be finalized.
https://jira.eduuni.fi/browse/OPHJOD-290
=> OPHJOD-290: PathProgress component

lib/components/Combobox/Combobox.stories.tsx, lib/components/Combobox/Combobox.tsx
* Actually use the input element to filter list contents
* Highlight list items when using the keyboard to select items
https://jira.eduuni.fi/browse/OPHJOD-625
=> OPHJOD-625: Filter combobox by writing

lib/components/Accordion/Accordion.tsx
- Add initial state prop to Accordion component
https://jira.eduuni.fi/browse/OPHJOD-628
=> OPHJOD-628: Add initial state prop to Accordion component

lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap, lib/components/InputField/InputField.stories.tsx, lib/components/InputField/InputField.test.tsx, lib/components/InputField/InputField.tsx, lib/components/InputField/__snapshots__/InputField.test.tsx.snap
* Change InputField padding to 16px like in Figma
* Change font to Arial for Datepicker input and InputField and help texts
* Fix InputField snapshot tests
https://jira.eduuni.fi/browse/OPHJOD-661
=> OPHJOD-661: Update padding and font for InputField and Datepicker

lib/components/Modal/Modal.tsx
* Make modal footer scrollable again
* Height is a bit more consistent
* Update grid columns from 6 to 3
https://jira.eduuni.fi/browse/OPHJOD-663
=> OPHJOD-663: Set fixed height for modal and make the footer scrollable

lib/components/Button/Button.stories.tsx, lib/components/Button/Button.tsx
* Make it possible for link components to resemble the DS button
https://jira.eduuni.fi/browse/OPHJOD-383
=> OPHJOD-383: Allow button component to be wrapped in a link

lib/components/Combobox/Combobox.test.tsx, lib/components/Combobox/Combobox.tsx, lib/components/Combobox/__snapshots__/Combobox.test.tsx.snap
- Update to use icon from library
- Update to have other icon shown when list is opened
https://jira.eduuni.fi/browse/OPHJOD-673
=> OPHJOD-673: Combobox to use icon from library

lib/components/Tag/Tag.stories.tsx, lib/components/Tag/Tag.tsx, lib/components/Tag/__snapshots__/Tag.test.tsx.snap, tailwind.config.ts
- Update Tag component to use sourceType instead of color
https://jira.eduuni.fi/browse/OPHJOD-626
=> OPHJOD-626: Update Tag component to use sourceType instead of color

lib/components/PathProgress/PathProgress.tsx
Add missing icons for PathProgress component.
https://jira.eduuni.fi/browse/OPHJOD-765
=> OPHJOD-675: Add missing icons for PathProgress

lib/components/Button/Button.tsx
* Added accent color variant to button, as https://jira.eduuni.fi/browse/OPHJOD-703 requires it
https://jira.eduuni.fi/browse/OPHJOD-703
=> OPHJOD-703: Add accent variant to button

lib/components/Slider/Slider.stories.tsx, lib/components/Slider/Slider.tsx
Add the missing `min-width` for the Slider component
https://jira.eduuni.fi/browse/OPHJOD-800
=> OPHJOD-800: Add min-width for Slider

lib/components/HeroCard/HeroCard.stories.tsx, lib/components/HeroCard/HeroCard.test.tsx, lib/components/HeroCard/HeroCard.tsx
- Refactor HeroCard to improve responsiveness
https://jira.eduuni.fi/browse/OPHJOD-803
=> OPHJOD-803: Refactor HeroCard to improve responsiveness

lib/components/Modal/Modal.tsx
Update Modal component to have smaller "margins" above & below of Modal
https://jira.eduuni.fi/browse/OPHJOD-728
=> OPHJOD-728: Update "margins" above & below of Modal

lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
Update RoundLinkButton min-width to match with the design.
Relates to the  fix PR on UI-side: Opetushallitus/jod-yksilo-ui/pull/179
https://jira.eduuni.fi/browse/OPHJOD-816
=> OPHJOD-816: Update RoundLinkButton min-width

lib/components/Footer/Footer.tsx
- Refactor footer to accept additional class name
https://jira.eduuni.fi/browse/OPHJOD-806
=> OPHJOD-806: Refactor footer to accept additional class name

lib/components/Button/Button.tsx
* Update background color for accent variant button when it's disabled
https://jira.eduuni.fi/browse/OPHJOD-805
=> OPHJOD-805: Update disabled background color for accent button

lib/components/Tag/Tag.tsx
- Refactor Tag to include optional title prop
https://jira.eduuni.fi/browse/OPHJOD-825
=> OPHJOD-825: Refactor Tag to include optional title prop

lib/components/Pagination/Pagination.tsx, lib/components/Pagination/__snapshots__/Pagination.test.tsx.snap
* Fixed the active page background in Pagination component
https://jira.eduuni.fi/browse/OPHJOD-840
=> OPHJOD-840: Fix active page background in Pagination

lib/components/Footer/Footer.stories.tsx, lib/components/Footer/Footer.test.tsx, lib/components/Footer/Footer.tsx, lib/components/Footer/__snapshots__/Footer.test.tsx.snap
- Refactor Footer to use JSX elements instead for logos
https://jira.eduuni.fi/browse/OPHJOD-807
=> OPHJOD-807: Refactor Footer to use JSX elements instead for logos

lib/components/Pagination/Pagination.test.tsx, lib/components/Pagination/Pagination.tsx, lib/components/Pagination/__snapshots__/Pagination.test.tsx.snap, lib/components/Slider/Slider.tsx
- Fix the Slider's width logic for mobile
- Remove "duplicate" first and last page buttons from Pagination; underlying Ark UI library already has always the first and last page shown, so no need to have same feature with additional two buttons.
https://jira.eduuni.fi/browse/OPHJOD-850
=> OPHJOD-850: Fix Slider and Pagination component on mobile

lib/components/InputField/InputField.test.tsx, lib/components/InputField/InputField.tsx, lib/components/InputField/__snapshots__/InputField.test.tsx.snap
Add `hideLabel` prop for InputField
Remove parens from the placeholder
More changes coming later as there are some questions in the air in the design which is the wanted design for the placeholder and it's font.
https://jira.eduuni.fi/browse/OPHJOD-790
=> OPHJOD-790: Add hideLabel prop for InputField

lib/components/Checkbox/Checkbox.stories.tsx, lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, lib/components/RadioButton/RadioButton.stories.tsx, lib/components/RadioButton/RadioButton.tsx
* Create bordered variant for radio button and checkbox
https://jira.eduuni.fi/browse/OPHJOD-881
=> OPHJOD-881: Add bordered variants to radio button and checkbox

lib/components/Modal/Modal.stories.tsx, lib/components/Pagination/Pagination.stories.tsx, lib/components/SelectionCard/SelectionCard.stories.tsx
* Fixed hook errors that appeared on some storybook stories. The issue was related to the use of "React.useState", nowdays we should use `useState` from `@storybook/preview-api`
https://jira.eduuni.fi/browse/OPHJOD-884
=> OPHJOD-884: Fix hook errors from stories

lib/components/SelectionCard/SelectionCard.tsx
Update the text size on SelectionCard when on mobile
Got the answer from design regarding this and did not see reason to make separate JIRA ticket for this.
https://jira.eduuni.fi/browse/OPHJOD-874
=> OPHJOD-874: Update font size for SelectionCard on mobile

lib/components/Pagination/Pagination.tsx, lib/main.ts
- Add `PageChangeDetails` type to be exported from the library.
- UI-side has hard time figuring out the correct type and it fails
The ark-ui update ticket:
https://jira.eduuni.fi/browse/OPHJOD-861
This actual fix/investigation ticket:
https://jira.eduuni.fi/browse/OPHJOD-945
=> OPHJOD-861: Add PageChangeDetails type to be exported

lib/components/PopupList/PopupList.tsx, lib/components/PopupList/__snapshots__/PopupList.test.tsx.snap
- Fix popup right padding
https://jira.eduuni.fi/browse/OPHJOD-887
=> OPHJOD-887: Fix popup right padding

lib/components/Datepicker/Datepicker.test.tsx, lib/components/Datepicker/Datepicker.tsx
* Fix datepicker not clearing the value when text input is emptied
https://jira.eduuni.fi/browse/OPHJOD-958
=> OPHJOD-958: Fix datepicker not being able to clear the value

lib/components/DiscussionCard/DiscussionCard.stories.tsx, lib/components/DiscussionCard/DiscussionCard.tsx, lib/main.ts
* Created the first version of DiscussionCard component
* Unit tests are delibaretly omitted because there's a high chance that the implementation will change once ohjaaja UI development will start and this component will be used.
https://www.figma.com/design/6M2LrpSCcB0thlFDaQAI2J/cx_jod_client?node-id=2217-8613&t=wQbfg5RSeRDJM45w-4
https://jira.eduuni.fi/browse/OPHJOD-848
=> OPHJOD-848: Create DiscussionCard component

lib/components/HeroCard/HeroCard.stories.tsx, lib/components/Pagination/Pagination.tsx, lib/components/SelectionCard/SelectionCard.test.tsx, lib/components/SelectionCard/SelectionCard.tsx, lib/components/Slider/Slider.tsx, lib/components/Textarea/Textarea.stories.tsx, lib/components/Textarea/Textarea.test.tsx, lib/components/Textarea/Textarea.tsx, lib/components/Textarea/__snapshots__/Textarea.test.tsx.snap, lib/hooks/useMediaQueries/index.ts, lib/main.ts, lib/vite-env.d.ts, tailwind.config.ts
- Enhance responsive design
- Add Textarea component
https://jira.eduuni.fi/browse/OPHJOD-896
=> OPHJOD-896

.github/workflows/build.yml, .storybook/preview-head.html
- Fix Poppins font
https://jira.eduuni.fi/browse/OPHJOD-1039
=> OPHJOD-1039: Fix Poppins font

lib/components/InputField/InputField.tsx, lib/components/Textarea/Textarea.tsx
- Add maxLength to InputField and Textarea
https://jira.eduuni.fi/browse/OPHJOD-1045
=> OPHJOD-1045: Add maxLength to InputField and Textarea

lib/components/HeroCard/HeroCard.tsx
- Refactor HeroCard to show content when sm size
https://jira.eduuni.fi/browse/OPHJOD-1037
=> OPHJOD-1037: Refactor HeroCard to show content when sm size

lib/components/Modal/Modal.stories.tsx, lib/components/Modal/Modal.tsx
* Fix modal content appearing at the bottom in mobile view
* Added storybook story that allows to dynamically set the modal contents (see screenshot). It allows to test the modal in different situations.
https://jira.eduuni.fi/browse/OPHJOD-1093
=> OPHJOD-1093: Display content at the top of the modal in mobile view

eslint.config.js, lib/components/Modal/Modal.stories.tsx, lib/components/Pagination/Pagination.tsx, lib/components/PathProgress/PathProgress.tsx, package-lock.json, package.json
* Updated the `eslint-plugin-sonarjs` package
https://jira.eduuni.fi/browse/OPHJOD-1116
=> OPHJOD-1116: Update eslint-plugin-sonarjs

lib/components/Modal/Modal.stories.tsx, lib/components/Modal/Modal.tsx
- Add modal variation without side panel
https://jira.eduuni.fi/browse/OPHJOD-1163
=> OPHJOD-1163: Add modal variation without side panel

lib/components/HeroCard/HeroCard.tsx
- Correct type definitions for HeroCard component
https://jira.eduuni.fi/browse/OPHJOD-1171
=> OPHJOD-1171: Correct type definitions for HeroCard component

lib/components/Textarea/Textarea.tsx
- Add onKeyDown prop to Textarea
https://jira.eduuni.fi/browse/OPHJOD-1143
=> OPHJOD-1143: Add onKeyDown prop to Textarea

package.json
- Update React to version 19
https://jira.eduuni.fi/browse/OPHJOD-1178
=> OPHJOD-1178: Update React to version 19

lib/components/CardCarousel/CardCarousel.stories.tsx, lib/components/CardCarousel/CardCarousel.tsx, lib/main.ts
* Created a carousel component for displaying MediaCard components
https://jira.eduuni.fi/browse/OPHJOD-1160
=> OPHJOD-1160: Create CardCarousel component

lib/components/CardCarousel/CardCarousel.stories.tsx, lib/components/CardCarousel/CardCarousel.tsx, lib/main.ts
* Turn `CardCarousel` gap into a prop. Makes it work better with Ohjaaja UI layout.
* Export `CardCarouselItem` type
https://jira.eduuni.fi/browse/OPHJOD-1203
=> OPHJOD-1203: Add gap prop to CardCarousel

lib/components/CardCarousel/CardCarousel.tsx
Fix the gap prop to actually affect the gap, not just calculations
https://jira.eduuni.fi/browse/OPHJOD-1203
=> OPHJOD-1203: Fix gap prop in CardCarousel

lib/components/Footer/Footer.tsx, lib/components/Footer/__snapshots__/Footer.test.tsx.snap
- Fix footer logos styles
https://jira.eduuni.fi/browse/OPHJOD-
=> OPHJOD-1210: Fix footer logos styles

lib/components/CardCarousel/CardCarousel.tsx
- Fix disabled cursor style
https://jira.eduuni.fi/browse/OPHJOD-1226
=> OPHJOD-1226: Fix disabled cursor style

lib/components/Datepicker/Datepicker.test.tsx, lib/components/Datepicker/Datepicker.tsx
Fix DatePicker causing crash
https://jira.eduuni.fi/browse/OPHJOD-1238
=> OPHJOD-1238: Fix DatePicker

lib/theme.css
- Add todo color variable to theme
https://jira.eduuni.fi/browse/OPHJOD-1263
=> OPHJOD-1263: Add todo color variable to theme

lib/components/MediaCard/MediaCard.stories.tsx, lib/components/MediaCard/MediaCard.test.tsx, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
* Update styling of `MediaCard` component
* Allow tags to increase the height of the card
* Limit label & description line count based on their length
* Change tag separator color
* Add some vertical padding to tags
https://jira.eduuni.fi/browse/OPHJOD-1243
=> OPHJOD-1243: Update MediaCard styling

lib/components/MediaCard/MediaCard.stories.tsx, lib/components/MediaCard/MediaCard.test.tsx, lib/components/MediaCard/MediaCard.tsx, lib/hooks/useMediaQueries/index.ts
- Added horizontal variant of the MediaCard for content listing pages
https://jira.eduuni.fi/browse/OPHJOD-1253
=> OPHJOD-1253: Add horizontal variant of the MediaCard

lib/components/CardCarousel/CardCarousel.stories.tsx, lib/components/CardCarousel/CardCarousel.test.tsx, lib/components/CardCarousel/CardCarousel.tsx, lib/theme.css, vitest.setup.ts
- Add test for CardCarousel and fix tab index bug
https://jira.eduuni.fi/browse/OPHJOD-1291
=> OPHJOD-1291: Add test for CardCarousel and fix tab index bug

lib/components/CardCarousel/CardCarousel.stories.tsx, lib/components/CardCarousel/CardCarousel.test.tsx, lib/components/CardCarousel/CardCarousel.tsx, lib/components/CardCarousel/__snapshots__/CardCarousel.test.tsx.snap, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
- Improve accessibility for CardCarousel
https://jira.eduuni.fi/browse/OPHJOD-1293
=> OPHJOD-1293: Improve accessibility for CardCarousel

lib/components/CardCarousel/CardCarousel.stories.tsx, lib/components/CardCarousel/CardCarousel.tsx, lib/components/CardCarousel/__snapshots__/CardCarousel.test.tsx.snap, lib/components/Modal/Modal.tsx
- Fix CardCarousel padding and margin
https://jira.eduuni.fi/browse/OPHJOD-1293
=> OPHJOD-1293: Fix CardCarousel padding and margin

lib/components/HeroCard/HeroCard.tsx, lib/docs/Spacing.mdx
- Fix spacing doc
https://jira.eduuni.fi/browse/OPHJOD-1226
=> OPHJOD-1226: Fix spacing doc

lib/components/Datepicker/Datepicker.test.tsx, lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap, lib/components/Datepicker/utils.test.ts, lib/components/Datepicker/utils.ts, lib/components/Modal/Modal.test.tsx, lib/utils.test.ts, lib/utils.ts, package-lock.json, package.json
* Fixed keyboard navigation issue where some of the buttons worked with either space or enter -> Now both can be used
* Fixed the issue where the keyboard navigation would stop working if user inputted a date outside the min/max year range
* Removed ForwardRef as it's not required since React 19
https://jira.eduuni.fi/browse/OPHJOD-1292
=> OPHJOD-1292: Fix a11y issues in Datepicker

lib/components/Checkbox/Checkbox.stories.tsx, lib/components/Checkbox/Checkbox.test.tsx, lib/components/Checkbox/Checkbox.tsx
- Revert label change as there was possiblity to have a component as a label and that went unnoticed.
- Improved documentation on that part and added a story for that case also.
https://jira.eduuni.fi/browse/OPHJOD-1340
=> OPHJOD-1340: Revert label change and improve documentation on that

lib/components/ConfirmDialog/ConfirmDialog.tsx, lib/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap, lib/components/Modal/Modal.tsx
Update Modal & ConfirmDialog to better support ESC handling
https://jira.eduuni.fi/browse/OPHJOD-1356
=> OPHJOD-1356: Update Modal & ConfirmDialog to better support ESC handling

lib/components/Button/Button.test.tsx, lib/components/Button/Button.tsx
Add support for ref prop in Button component.
https://jira.eduuni.fi/browse/OPHJOD-1355
=> OPHJOD-1355: Add support for ref prop in Button component

lib/components/PathProgress/PathProgress.stories.tsx, lib/components/PathProgress/PathProgress.tsx, lib/main.ts
Update PathProgress component
https://jira.eduuni.fi/browse/OPHJOD-1337
=> OPHJOD-1337: Update PathProgress component

lib/main.ts
Update to export ComboboxOptionsData
https://jira.eduuni.fi/browse/OPHJOD-1399
=> OPHJOD-1399: Update to export ComboboxOptionsData

lib/components/Tooltip/Tooltip.stories.tsx
- Fix Tooltip's example story
- Add few more example stories for Tooltip
The example code for the story was not correctly shown. This should fix it and showing how it is used.
Tooltip should not be on a button that already has existing action
https://jira.eduuni.fi/browse/OPHJOD-1404
=> OPHJOD-1404: Fix Tooltip's example story

lib/theme.css
* Add secondary-2 color variants
https://jira.eduuni.fi/browse/OPHJOD-1361
=> OPHJOD-1361: Add secondary-2 colors

lib/components/Pagination/Pagination.test.tsx, lib/components/Pagination/__snapshots__/Pagination.test.tsx.snap, lib/components/Slider/Slider.test.tsx, package-lock.json, package.json
Update `@ark-ui/react` and tests to work after the update
https://jira.eduuni.fi/browse/OPHJOD-1428
https://jira.eduuni.fi/browse/OPHJOD-851
=> OPHJOD-1428: Update @ark-ui

lib/components/Button/Button.tsx
- Add className prop to Button
https://jira.eduuni.fi/browse/OPHJOD-1442
=> OPHJOD-1442: Add className prop to Button

lib/components/MediaCard/MediaCard.stories.tsx, lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
This PR refactors the structure of the MediaCard component to eliminate nested <a> elements. Previously, links inside the card  ended up nested within the main card link, which is invalid HTML and causes accessibility and usability issues.
https://jira.eduuni.fi/browse/OPHJOD-1495
=> OPHJOD-1495: Refactor MediaCard to avoid nested links

lib/components/NavigationMenu/Backdrop.tsx, lib/components/NavigationMenu/ExternalLinkSections.tsx, lib/components/NavigationMenu/LanguageSelection.tsx, lib/components/NavigationMenu/MenuList.tsx, lib/components/NavigationMenu/MenuSeparator.tsx, lib/components/NavigationMenu/NavigationMenu.stories.tsx, lib/components/NavigationMenu/NavigationMenu.test.tsx, lib/components/NavigationMenu/NavigationMenu.tsx, lib/components/NavigationMenu/Placeholder.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap, lib/components/NavigationMenu/index.ts, lib/components/NavigationMenu/menuFocusManager.ts, lib/components/NavigationMenu/types.d.ts, lib/main.ts
Add NavigationMenu component
https://jira.eduuni.fi/browse/OPHJOD-1454
=> OPHJOD-1454: Add NavigationMenu component

README.md
Add info how to add the package to a project.
Add info how to add the package to a project.
=> OPHJOD-1533: Update README

lib/components/WizardProgress/WizardProgress.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap
- Update WizardProgress to match new design
- text color
- text size changed (uses the new token)
https://jira.eduuni.fi/browse/OPHJOD-1522
=> OPHJOD-1522: Update WizardProgress with new design

lib/components/NavigationMenu/Backdrop.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap
Update NavigationMenu's backdrop color
https://jira.eduuni.fi/browse/OPHJOD-1544
=> OPHJOD-1544: Update NavigationMenu backdrop color

lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap
Update Datepicker styles
- Change to different calendar icon
- Placeholder text now uses token
https://jira.eduuni.fi/browse/OPHJOD-1523
=> OPHJOD-1523: Update Datepicker styles

lib/components/NavigationMenu/NavigationMenu.stories.tsx
- Update title to reflect correct category
https://jira.eduuni.fi/browse/OPHJOD-1540
=> OPHJOD-1540: Update title to reflect correct category

lib/components/RoundButton/RoundButton.tsx, lib/components/RoundButton/__snapshots__/RoundButton.test.tsx.snap, lib/components/RoundLinkButton/RoundLinkButton.tsx, lib/components/RoundLinkButton/__snapshots__/RoundLinkButton.test.tsx.snap
Update RoundButton & RoundLinkButton token use; remove the use of removed token `text-button-sm-mobile`
https://jira.eduuni.fi/browse/OPHJOD-1548
=> OPHJOD-1548: Update RoundButton & RoundLinkButton token use

lib/components/Tag/Tag.tsx, lib/components/Tag/__snapshots__/Tag.test.tsx.snap, lib/theme.css
Update Tag-component
- Update to use `text-body-sm` token
- `text-tag` removed from design system
- Update colors used in tag based on `sourceType`
https://jira.eduuni.fi/browse/OPHJOD-1526
=> OPHJOD-1526: Update Tag component and update/delete related tokens

lib/components/InputField/InputField.stories.tsx, lib/components/InputField/InputField.tsx, lib/components/InputField/__snapshots__/InputField.test.tsx.snap
Update InputField
- Update placholder text color
- Add `requiredText` prop to be shown after the label
https://jira.eduuni.fi/browse/OPHJOD-1524
=> OPHJOD-1524: Update InputField component style + add requiredText prop

lib/components/Toggle/Toggle.stories.tsx, lib/components/Toggle/Toggle.test.tsx, lib/components/Toggle/Toggle.tsx, lib/components/Toggle/__snapshots__/Toggle.test.tsx.snap, lib/main.ts
Created a `Toggle` component
https://jira.eduuni.fi/browse/OPHJOD-1551
On:
On with hover:
Off:
Disabled (no design for this so I improvised):
=> OPHJOD-1551: Create Toggle component

lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/theme.css
Update Button styles
- adjust all sizes to use Poppins font
- update pressed state for `accent`
- update paddings for all sizes
https://jira.eduuni.fi/browse/OPHJOD-1554
=> OPHJOD-1554: Update Button styles

lib/components/IconButton/IconButton.stories.tsx, lib/components/IconButton/IconButton.test.tsx, lib/components/IconButton/IconButton.tsx, lib/components/IconButton/__snapshots__/IconButton.test.tsx.snap, lib/main.ts
Adds an IconButton component that can be used, for example, as filter and sort buttons in views like Ohjaajan työpöydän Suosikit
https://jira.eduuni.fi/browse/OPHJOD-1591
=> OPHJOD-1591: Add IconButton

lib/components/HeroCard/HeroCard.stories.tsx, lib/components/HeroCard/HeroCard.test.tsx, lib/components/HeroCard/HeroCard.tsx, lib/components/HeroCard/__snapshots__/HeroCard.test.tsx.snap
Update HeroCard
https://jira.eduuni.fi/browse/OPHJOD-1583
=> OPHJOD-1583: Update HeroCard

lib/components/NavigationMenu/MenuList.tsx, lib/components/NavigationMenu/NavigationMenu.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap
- Add some optional props to navigation menu
https://jira.eduuni.fi/browse/OPHJOD-1549
=> OPHJOD-1549: Add some optional props to navigation menu

lib/components/HeroCard/HeroCard.tsx, lib/components/HeroCard/__snapshots__/HeroCard.test.tsx.snap
- Remove transition effects from HeroCard
https://jira.eduuni.fi/browse/OPHJOD-1620
=> OPHJOD-1620: Remove transition effects from HeroCard

lib/components/NavigationMenu/ExternalLinkSections.tsx, lib/components/NavigationMenu/MenuSeparator.tsx, lib/components/NavigationMenu/NavigationMenu.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap
- Refactor ExternalLinkSections to include MenuSeparator
https://jira.eduuni.fi/browse/OPHJOD-1592
=> OPHJOD-1592: Refactor ExternalLinkSections to include MenuSeparator

lib/components/NavigationMenu/MenuList.tsx, lib/components/NavigationMenu/NavigationMenu.stories.tsx, lib/components/NavigationMenu/NavigationMenu.tsx
- Add support for displaying titles in the menu
https://jira.eduuni.fi/browse/OPHJOD-1635
=> OPHJOD-1635: Add support for displaying titles in the menu

lib/components/Footer/Footer.stories.tsx, lib/components/Footer/Footer.test.tsx, lib/components/Footer/Footer.tsx, lib/components/HeroCard/HeroCard.tsx
- Update Footer to have `onClick` prop
- Remove `feedbackTo` & `FeedbackLinkComponent` props from Footer.
- Add support for `onClick` for HeroCard
https://jira.eduuni.fi/browse/OPHJOD-1677
=> OPHJOD-1677: Update Footer & HeroCard to support onClick

lib/components/RadioButton/RadioButton.stories.tsx, lib/components/RadioButton/RadioButton.tsx, lib/components/RadioButton/RadioButtonGroup.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
- Update RadioButton component to match the design
- Remove the `variant` prop; it now always has border.
https://jira.eduuni.fi/browse/OPHJOD-1678
=> OPHJOD-1678: Update RadioButton

lib/components/NavigationMenu/NavigationMenu.tsx, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap
- Fix NavigationMenu component outline bug 
- Add margin between logo and frontpage link as in the design
https://jira.eduuni.fi/browse/OPHJOD-1693
=> OPHJOD-1693: Fix NavigationMenu outline and margin

lib/components/WizardProgress/WizardProgress.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap
Update WizardProgress to match latest design
https://jira.eduuni.fi/browse/OPHJOD-1733
=> OPHJOD-1733: Update WizardProgress to match latest design

lib/components/MatomoTracker/MatomoTracker.stories.tsx, lib/components/MatomoTracker/MatomoTracker.test.tsx, lib/components/MatomoTracker/MatomoTracker.tsx, lib/components/MatomoTracker/loadMatomo.ts, lib/main.ts
- Add MatomoTracker
https://jira.eduuni.fi/browse/OPHJOD-1687
=> OPHJOD-1687: Add MatomoTracker

lib/components/Button/Button.stories.tsx, lib/components/Button/Button.test.tsx, lib/components/Button/Button.tsx, lib/components/Button/__snapshots__/Button.test.tsx.snap, lib/components/HeroCard/HeroCard.tsx, lib/components/HeroCard/__snapshots__/HeroCard.test.tsx.snap, lib/components/NavigationMenu/__snapshots__/NavigationMenu.test.tsx.snap, lib/components/NavigationMenu/components/ExternalLinkSections.tsx, lib/components/NavigationMenu/components/LanguageSelection.tsx, lib/components/NavigationMenu/components/MenuList.tsx, lib/theme.css, lib/utils.ts
* Updated `Button` component to match latest design.
* Created a story that shows all variants of the button, much easier to make changes.
https://jira.eduuni.fi/browse/OPHJOD-1769
=> OPHJOD-1769: Update Button component to match latest design

lib/components/Toast/Toast.stories.tsx, lib/components/Toast/Toast.tsx, lib/components/Toast/__snapshots__/Toast.test.tsx.snap
Updated `Toast` component to match latest design
https://jira.eduuni.fi/browse/OPHJOD-1767
=> OPHJOD-1767: Update Toast component to match latest design

lib/components/Breadcrumb/Breadcrumb.stories.tsx, lib/components/Breadcrumb/Breadcrumb.test.tsx, lib/components/Breadcrumb/Breadcrumb.tsx, lib/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, lib/main.ts
* Created a Breadcrumb component
https://jira.eduuni.fi/browse/OPHJOD-1628
=> OPHJOD-1628: Create Breadcrumb component

package.json
Export CSS files
https://jira.eduuni.fi/browse/OPHJOD-1740
=> OPHJOD-1740: Add CSS files to exports

lib/components/Modal/Modal.tsx
- Adjust margin for progress
https://jira.eduuni.fi/browse/OPHJOD-1688
=> OPHJOD-1688: Adjust margin for progress

.github/workflows/build.yml, .nvmrc, package-lock.json, package.json
- Update Node.js version to lts/jod
https://jira.eduuni.fi/browse/OPHJOD-1779
=> OPHJOD-1779: Update Node.js version to lts/jod

lib/main.ts
Export `useNoteStack` hook in `main.ts`
https://jira.eduuni.fi/browse/OPHJOD-1766
=> OPHJOD-1766: Export useNoteStack in main.ts

lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Fix Checkbox icon, so that the 'image' is not read when using Quick Nav or similar mode with screenreaders.
https://jira.eduuni.fi/browse/OPHJOD-1880
=> OPHJOD-1880: Fix Checkbox checked icon for screenreader

lib/components/Combobox/Combobox.test.tsx, lib/components/Combobox/Combobox.tsx, lib/components/Combobox/__snapshots__/Combobox.test.tsx.snap
- Add `className` prop for Combobox
- add `aria-label` for the button opening the menu
- small renaming to better describe the actual purpose of id used.
https://jira.eduuni.fi/browse/OPHJOD-1903
https://jira.eduuni.fi/browse/OPHJOD-1905
=> OPHJOD-1905: Update Combobox; add className prop, having aria-label

lib/components/Select/Select.stories.tsx, lib/components/Select/Select.test.tsx, lib/components/Select/Select.tsx, lib/components/Select/__snapshots__/Select.test.tsx.snap, lib/main.ts
Add Select component
https://jira.eduuni.fi/browse/OPHJOD-1954
=> OPHJOD-1954: Add Select component

lib/components/MediaCard/MediaCard.tsx, lib/components/MediaCard/__snapshots__/MediaCard.test.tsx.snap
Adjust MediaCard: update height, reduce title font, allow 3-line labels and descriptions, standardize image sizes (261×147 portrait, 255×143 landscape)
https://jira.eduuni.fi/browse/OPHJOD-2078
=> OPHJOD-2078: Refactor MediaCard component

lib/components/Button/Button.stories.tsx, lib/components/Button/Button.tsx, lib/components/IconButton/IconButton.stories.tsx, lib/components/IconButton/IconButton.test.tsx, lib/components/IconButton/IconButton.tsx, lib/components/IconButton/__snapshots__/IconButton.test.tsx.snap
* Refactored/replaced the old `IconButton` with a new implementation based on new design
* The old icon button was only used in 2 components in ohjaaja-ui, and they can easily be replaced with `Button`
https://jira.eduuni.fi/browse/OPHJOD-1808
=> OPHJOD-1808: Refactor IconButton component

lib/components/NavigationBar/NavigationBar.tsx, lib/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
Add "Beta" and "Testausversio" text to header
https://jira.eduuni.fi/browse/OPHJOD-2136
=> OPHJOD-2137: Add "Beta" and "Testausversio" text to header

lib/components/NavigationBar/NavigationBar.tsx
* Align service bar contents with header. Tested in different screen sizes.
https://jira.eduuni.fi/browse/OPHJOD-2234
=> OPHJOD-2234: Align service bar contents with header

lib/components/Datepicker/Datepicker.tsx
Add hover underline to datepicker header part to make it appear more interactive
https://jira.eduuni.fi/browse/OPHJOD-2019
=> OPHJOD-2019: Add hover underline to datepicker header part

lib/components/HeroCard/HeroCard.test.tsx, lib/components/HeroCard/__snapshots__/HeroCard.test.tsx.snap, lib/components/Note/Note.test.tsx, lib/components/Note/__snapshots__/Note.test.tsx.snap, lib/components/PopupList/PopupList.test.tsx, lib/components/PopupList/__snapshots__/PopupList.test.tsx.snap, lib/components/ProgressIndicatorCard/ProgressIndicatorCard.test.tsx, lib/components/ProgressIndicatorCard/__snapshots__/ProgressIndicatorCard.test.tsx.snap, lib/components/RadioButton/RadioButton.test.tsx, lib/components/RadioButton/RadioButtonGroup.test.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, lib/components/SkipLink/SkipLink.test.tsx, lib/components/SkipLink/__snapshots__/SkipLink.test.tsx.snap, lib/components/Tag/Tag.test.tsx, lib/components/Tag/__snapshots__/Tag.test.tsx.snap, lib/components/Textarea/Textarea.test.tsx, lib/components/Textarea/__snapshots__/Textarea.test.tsx.snap, lib/components/Toast/Toast.test.tsx, lib/components/Toast/__snapshots__/Toast.test.tsx.snap, lib/components/WizardProgress/WizardProgress.test.tsx, lib/components/WizardProgress/__snapshots__/WizardProgress.test.tsx.snap
- Restore some snapshots
https://jira.eduuni.fi/browse/OPHJOD-1889
=> OPHJOD-1889: Restore some snapshots

lib/components/Checkbox/Checkbox.tsx, lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, lib/components/Combobox/Combobox.tsx, lib/components/Combobox/__snapshots__/Combobox.test.tsx.snap, lib/components/Datepicker/Datepicker.tsx, lib/components/Datepicker/__snapshots__/Datepicker.test.tsx.snap, lib/components/RadioButton/RadioButtonGroup.tsx, lib/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, lib/components/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, lib/components/Textarea/Textarea.tsx
* Add `required` and `aria-required` attributes to all form components that didn't have them already
https://jira.eduuni.fi/browse/OPHJOD-2033
=> OPHJOD-2033: Add required and aria-required attributes to form components

lib/components/Chatbot/Chatbot.stories.tsx, lib/components/Chatbot/Chatbot.tsx
Add disclaimer text to chatbot
https://jira.eduuni.fi/browse/OPHJOD-2291
=> OPHJOD-2291: Add disclaimer text to chatbot
